[pytest]
addopts = -ra --headed
markers =
    smoke : быстрые smoke-тесты
    ui : UI тесты
    api : API тесты
    mocked : замокированные API тесты
    integration : API тесты, которые ходят в сеть
